name: pruebas ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: mostrar mensaje
        run: echo "hola mundo"
      - name: fecha
        run: date