name: Ci con Issues y PRs

on:
  issues:
     types: [opened, edited, closed, reopened, deleted]  
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  #job 1: verificar el código
  verificar-codigo:
    runs-on: ubuntu-latest

    steps:
      - name: Ckeckout del repositorio
        uses: actions/checkout@v3
        

      - name: mostrar archivos
        run: ls -R